[PREP]
data_dir = "data/WAV"
output_dir = "data/preprocessed"
audio_format = "wav"
spect_output_dir = "data/preprocessed/spec"

[SPECT_PARAMS]
fft_size = 1024
step_size = 480
freq_cutoffs = [ 750, 18000,]
transform_type = "log_spect"
spect_key = "s"
freqbins_key = "f"
timebins_key = "t"
audio_path_key = "audio_path"

[DATALOADER]
window_size = 800

[PREDICT]
device = "cuda"
num_workers = 2
models = [ "TweetyNet",]
batch_size = 128
checkpoint_path = "model/TweetyNet/checkpoints/max-val-acc-checkpoint.pt>"
labelmap_path = "model/labelmap.json"
spect_scaler_path = "model/StandardizeSpect"
output_dir = "results/predictions"
annot_csv_filename = "predictions.csv"

[TweetyNet.network]
hidden_size = 512
